# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1291, 797)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bg1 = QtWidgets.QLabel(self.centralwidget)
        self.bg1.setGeometry(QtCore.QRect(0, 0, 1301, 801))
        self.bg1.setText("")
        self.bg1.setPixmap(QtGui.QPixmap("D:/jarvis material/blackbackground.png"))
        self.bg1.setScaledContents(True)
        self.bg1.setObjectName("bg1")
        self.Gif1 = QtWidgets.QLabel(self.centralwidget)
        self.Gif1.setGeometry(QtCore.QRect(0, -20, 431, 161))
        self.Gif1.setText("")
        self.Gif1.setPixmap(QtGui.QPixmap("D:/jarvis material/Gif1.gif"))
        self.Gif1.setScaledContents(True)
        self.Gif1.setObjectName("Gif1")
        self.Gif2 = QtWidgets.QLabel(self.centralwidget)
        self.Gif2.setGeometry(QtCore.QRect(450, 190, 391, 381))
        self.Gif2.setText("")
        self.Gif2.setPixmap(QtGui.QPixmap("D:/jarvis material/Gif2.gif"))
        self.Gif2.setScaledContents(True)
        self.Gif2.setObjectName("Gif2")
        self.Gif3 = QtWidgets.QLabel(self.centralwidget)
        self.Gif3.setGeometry(QtCore.QRect(960, 20, 391, 221))
        self.Gif3.setText("")
        self.Gif3.setPixmap(QtGui.QPixmap("D:/jarvis material/Gif3.gif"))
        self.Gif3.setScaledContents(True)
        self.Gif3.setObjectName("Gif3")
        self.Gif4 = QtWidgets.QLabel(self.centralwidget)
        self.Gif4.setGeometry(QtCore.QRect(1020, 400, 311, 411))
        self.Gif4.setText("")
        self.Gif4.setPixmap(QtGui.QPixmap("D:/jarvis material/Gif4.gif"))
        self.Gif4.setScaledContents(True)
        self.Gif4.setObjectName("Gif4")
        self.Gif5 = QtWidgets.QLabel(self.centralwidget)
        self.Gif5.setGeometry(QtCore.QRect(-10, 470, 281, 321))
        self.Gif5.setText("")
        self.Gif5.setPixmap(QtGui.QPixmap("D:/jarvis material/Gif5.gif"))
        self.Gif5.setScaledContents(True)
        self.Gif5.setObjectName("Gif5")
        self.nameframe = QtWidgets.QLabel(self.centralwidget)
        self.nameframe.setGeometry(QtCore.QRect(450, 20, 381, 91))
        self.nameframe.setText("")
        self.nameframe.setPixmap(QtGui.QPixmap("D:/jarvis material/frame.jpg"))
        self.nameframe.setScaledContents(True)
        self.nameframe.setObjectName("nameframe")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(540, 40, 211, 51))
        self.name.setText("")
        self.name.setPixmap(QtGui.QPixmap("D:/jarvis material/jarvis name.jpg"))
        self.name.setScaledContents(True)
        self.name.setObjectName("name")
        self.gifframe = QtWidgets.QLabel(self.centralwidget)
        self.gifframe.setGeometry(QtCore.QRect(1040, 380, 261, 411))
        self.gifframe.setText("")
        self.gifframe.setPixmap(QtGui.QPixmap("D:/jarvis material/gif frame.png"))
        self.gifframe.setScaledContents(True)
        self.gifframe.setObjectName("gifframe")
        self.timeframe = QtWidgets.QLabel(self.centralwidget)
        self.timeframe.setGeometry(QtCore.QRect(0, 170, 281, 61))
        self.timeframe.setText("")
        self.timeframe.setPixmap(QtGui.QPixmap("D:/jarvis material/time frame.jpg"))
        self.timeframe.setScaledContents(True)
        self.timeframe.setObjectName("timeframe")
        self.dateframe = QtWidgets.QLabel(self.centralwidget)
        self.dateframe.setGeometry(QtCore.QRect(0, 260, 281, 71))
        self.dateframe.setText("")
        self.dateframe.setPixmap(QtGui.QPixmap("D:/jarvis material/date frame.jpg"))
        self.dateframe.setObjectName("dateframe")
        self.timetextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.timetextBrowser.setGeometry(QtCore.QRect(60, 170, 251, 41))
        self.timetextBrowser.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 18pt \"OCR A Extended\";\n"
"border:none;"
"color:white")
        self.timetextBrowser.setObjectName("timetextBrowser")
        self.datetextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.datetextBrowser.setGeometry(QtCore.QRect(60, 270, 251, 41))
        self.datetextBrowser.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 18pt \"OCR A Extended\";\n"
"border:none;"
"color:white")
        self.datetextBrowser.setObjectName("datetextBrowser")
        self.startbuttonframe = QtWidgets.QLabel(self.centralwidget)
        self.startbuttonframe.setGeometry(QtCore.QRect(380, 700, 251, 81))
        self.startbuttonframe.setText("")
        self.startbuttonframe.setPixmap(QtGui.QPixmap("D:/jarvis material/start button frame.jpg"))
        self.startbuttonframe.setScaledContents(True)
        self.startbuttonframe.setObjectName("startbuttonframe")
        self.stopbuttonframe = QtWidgets.QLabel(self.centralwidget)
        self.stopbuttonframe.setGeometry(QtCore.QRect(650, 700, 251, 81))
        self.stopbuttonframe.setText("")
        self.stopbuttonframe.setPixmap(QtGui.QPixmap("D:/jarvis material/stop button frame.jpg"))
        self.stopbuttonframe.setScaledContents(True)
        self.stopbuttonframe.setObjectName("stopbuttonframe")
        self.startpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.startpushButton.setGeometry(QtCore.QRect(430, 710, 151, 61))
        self.startpushButton.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"text-decoration: underline;\n"
"font: 20pt \"OCR A Extended\";\n"
"font: 20pt \"OCR A Extended\";")
        self.startpushButton.setObjectName("startpushButton")
        self.stoppushButton = QtWidgets.QPushButton(self.centralwidget)
        self.stoppushButton.setGeometry(QtCore.QRect(700, 710, 151, 61))
        self.stoppushButton.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"text-decoration: underline;\n"
"font: 20pt \"OCR A Extended\";\n"
"font: 20pt \"OCR A Extended\";")
        self.stoppushButton.setObjectName("stoppushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startpushButton.setText(_translate("MainWindow", "START"))
        self.stoppushButton.setText(_translate("MainWindow", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
